/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package meuprimeiroprojeto;

public class Principal {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Principal().getGreeting());
        System.out.println(new Principal().getGreeting());
    }
}
